name: unit_testing
# This package is not intended to be published
publish_to: none
description: >
  This package contains classes to define data structures for Dart Json Mapper Unit Tests.
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  naked_mapper:
dev_dependencies:
  build_runner:
dependency_overrides:
  naked_mapper:
    path: ../../mapper