builders:
  naked_mapper:
    target: ":naked_mapper"
    import: "package:naked_mapper/builder_factory.dart"
    builder_factories: ["dartJsonMapperBuilder"]
    build_extensions: {".dart": [".mapper.g.dart"]}
    auto_apply: root_package
    build_to: source
    defaults:
      options:
        iterables: List, Set
        extension: .mapper.g.dart
        formatted: false
      generate_for:
        exclude:
          - lib/**.dart
        include:
          - benchmark/**.dart
          - bin/**.dart
          - test/_*.dart
          - example/**.dart
          - lib/main.dart
          - tool/**.dart
          - web/**.dart

targets:
  $default:
    builders:
      naked_mapper:
        options:
          iterables: List, Set
        generate_for:
          - example/**.dart
      reflectable:
        generate_for:
          - no/files