targets:
  $default:
    builders:
      naked_mapper:
        options:
          iterables: List, Set
        generate_for:
          - test/unit/_test.dart
      reflectable:
        generate_for:
          - no/files