name: performance_test
# This package is not intended to be published
publish_to: none
description: >
  This package contains performance tests for the following JSON interoperability libraries:
  - JsonSerializable https://pub.dev/packages/json_serializable
  - BuiltValue https://pub.dev/packages/built_value
  - DartJsonMapper https://pub.dev/packages/naked_mapper
  And unit tests for DartJsonMapper
environment:
  sdk: '>=2.13.0 <3.0.0'
dependencies:
  naked_mapper:
  json_annotation: 4.1.0
  built_value: 8.1.2
  intl: ^0.17.0
dev_dependencies:
  json_serializable: 5.0.0
  built_value_generator: 8.1.2
  lints:
  build_runner:
  build_test:
  test:
dependency_overrides:
  unit_testing:
    path: ../models/unit_testing
  starlink:
    path: ../models/starlink
  naked_mapper:
    path: ../mapper